name: render pdf
on:
  push:

jobs:
  render:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2 
      - name: Install dependencies
        run: pip install nbformat nbclient ipykernel numpy 
      - name: Install TinyTex
        run: quarto install tool tinytex
      - name: Render PDF
        run: quarto render RSE_LAB.ipynb --to pdf --execute 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-document
          path: RSE_LAB.pdf
